#include "hal_data.h"

const char provisionHtml[] BSP_PLACE_IN_SECTION(".qspi_flash") =
        "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\"><title>IOT Monitoring Kit Configuration</"
        "title><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><style> #content,#footer{ma"
        "x-width:660px;margin:0 auto}#content,#footer,body{margin:0 auto}*{-webkit-box-sizing:border-box;-moz"
        "-box-sizing:border-box;box-sizing:border-box}body{font-family:Verdana,Arial,sans-serif;padding:0 0 2"
        "0px}#page{background:#fff;padding:20px;font-size:11pt}#page td{font-size:10pt}#title{font-weight:700"
        ";color:#000;margin:20px 0;text-align:center}#title .left{float:left;text-align:left}#footer{height:1"
        "6px;padding:3px 5px 20px;color:#888;font-size:.9em;text-align: center}#content a:hover{color:#d33;te"
        "xt-decoration:underline}.rounded_container{display:block;position:relative;border:2px solid #000;-we"
        "bkit-border-radius:15px;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-sel"
        "ect:none;font-size:12pt;-webkit-transition:height .5s;-moz-transition:height .5s;transition:height ."
        "5s;padding:12px 0 0}.rounded_container table tr{width:9em}.text-right{text-align:right}.join_button{"
        "text-indent:5;font-family:Arial;font-style:normal;text-align:center;width:100px;height:30px;margin:1"
        "0px 0 5px}.ssid1{width:213px}.logo{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;disp"
        "lay:-moz-box;display:flex;-webkit-box-pack:justify;-webkit-justify-content:space-between;-ms-flex-pa"
        "ck:justify;-moz-box-pack:justify;justify-content:space-between;-webkit-box-align:center;-webkit-alig"
        "n-items:center;-ms-flex-align:center;-moz-box-align:center;align-items:center;margin-left:auto;margi"
        "n-right:auto}img{display:block;height:auto;max-width:100%}@media (max-width:660px){.logo{display:blo"
        "ck;text-align:center;margin-left:auto;margin-right:auto}.logo img{margin:10px auto}.rounded_containe"
        "r table{width:100%}.rounded_container table tr{width:auto}.ssid1{width:100%}}table{margin-left:auto;"
        "margin-right:auto}.grey_text{color:#888;font-size:.8em}.align_right{text-align: right}.rounded_conta"
        "iner iframe{border:0;overflow:hidden;width:100%} </style><script>function joinNetwork(){var ssid=doc"
        "ument.getElementById('s').value;if(ssid.length<=0){alert('Please enter a valid SSID.');return;}docum"
        "ent.getElementById(\"ssid\").value=ssid;var sec=document.getElementById('am').value;document.getElemen"
        "tById(\"sec\").value=sec;var key=document.getElementById('k').value;document.getElementById(\"key\").val"
        "ue=key;var mqttprojectid=document.getElementById('m').value;if(mqttprojectid.length<=0){alert('Pleas"
        "e enter a valid mqtt project id.');return;}document.getElementById(\"mqttprojectid\").value=mqttprojec"
        "tid;var mqttuserid=document.getElementById('u').value;if(mqttuserid.length<=0){alert('Please enter a"
        " valid user_mqtt_id.');return;}document.getElementById(\"mqttuserid\").value=mqttuserid;var apikey=doc"
        "ument.getElementById('a').value;if(apikey.length<=0){alert('Please enter a valid api_key.');return;}"
        "document.getElementById(\"apikey\").value=apikey;var password=document.getElementById('p').value;if(pa"
        "ssword.length<=0){alert('Please enter a valid api_password.');return;}document.getElementById(\"passw"
        "ord\").value=password;window.location.hash='s='+ssid+'&am='+sec+'&m='+mqttprojectid+'&u='+mqttuserid+"
        "'&a='+apikey+'&p='+password;document.kickoff.submit();}function fillInputHashParams(){var hashParams"
        "=window.location.hash.substr(1).split('&');for(var i=0;i<hashParams.length;i++){var p=hashParams[i]."
        "split('=');if(p.length==1){break;}document.getElementById(p[0]).value=decodeURIComponent(p[1]);}}win"
        "dow.onload=fillInputHashParams;window.onhashchange=fillInputHashParams;</script></head><body><div id"
        "=\"page\"><div id=\"content\"><img class=\"logo\" src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJgAA"
        "AAdCAYAAABWv6VKAAANbklEQVR42u1bCXCV1RW+UWSzdkFQcINSKYtYQax2wLFMaWmLFFSMlhYikISXlX2HYlRssSy1FMhKIsiiA"
        "dSC0s5Ijcgi8PJCYAggWyi2uCBFRGQs4N/ve+/ccOb/895LIhZn8u7Mmfvfc8/dv/+cc8//nomlWPr/pNzSq0BNv3Kat66RiaV6l"
        "LJKGgjAJpmc0lMmN1CJZ9JhlCtBnmc3r7o6d730eRL9F4bGda4wsVQPUokjAPP/0Sw/5Jj8MieYv3DEMSsqkYNUDtJ1JJdcGNmCc"
        "scsO+AAYOtiAKtXACuxAHvaLNnnID9r8kpfQl4IWoLnxSYHlFcLylFtckufw/NS5B+xf/BeiQGsvgJsKTVM6WlTVNHyUg8DkFVAk"
        "7H/l2MAq9cAC5w2C/3tqxONzypuaIqLrwxHwXpvihMHf69ZcTgGsBjAAqeb5237PllJqSN/MHz48CzQ71JSUu4O4iIr6wqS7kLzI"
        "HsP5UPtMm4nr1vu2hoBzHGcOPTTgMRnEyHJmA169uzJ+VfJxsfHX0memyyf/ar2HhmSWp8nWRnXPNQcPMmu6QrdB3m6n3BtOS/VP"
        "mrii86LG/OLzw7GCbOfrKNMpP5ZRxl1Jrpv5iRd5vmGBVjrBRs6kpWckpY8btw4JzMz0wFgLvh8vhS9STpnYn1ycvIXGRkZDtsl+"
        "XyJ5PfMKv5GdIB5D8iCoYZ84UVPNTmsSEDTY0Yt133eNZeV/SQQooIvTAprVThnbzl6EtlqAdYmd0uHkAbLGJSenk5wnUlNTXUAH"
        "D4vAl3Fep2DCllPOcqzXXJKym+jAUxvPLRkG4B0ECkpKemm6sCgNGUHyCVAbiDaXUfekCFDGoPXHyB/BPlDyAdYkvKv0e578jLcg"
        "efHQPGURx+PIH8Q1D0xMbGZBpoauyHaPYwxe1oeZO9mP3gJv2lBoNeUlpbWEn0OA91m5wj5B1Aegr7uiwTMwYMHX835sX9aEFsXE"
        "TgLA91wkZqM83wetCJ4rvmBnxitsWwqKmmM83jA5AWGmEJ/Ww/IZK/RvqPJKxtmFpXdUAWcnLJeJsc/0ORsf8jk+QdcpMCDQX6Bv"
        "2s4J/8iwHxpCQQNtRIWeQzkjBw5kgAKYHPaUYY5y8InHbNazOdLHVQTgImJMTi4xFGjRjmjR492CFjyxAR6tADq36BcaBxfL+G1A"
        "v13xIgRnGeQ2B9z8iZMmMB+x4vs3LFjx1I7V8kwJ/EFwRqyAYaWrhepOQDD8baxLLznqa0BgM4WkHpN6OeXEydOZJ9PqjmekXE+w"
        "fgt9Lr0mjFOIuc1ZswYjrlU9e8FV/7W66EcVpml+xka4m39C+z1ObPsIMuMDmwx2f7ONqgeAtj2lnj+zKz8F8+lnFiwANJy6Gu6W"
        "XvSAXD62zFRt9u8eNRh/7y8WSKGKIs2y2sEMGoi0VxPYpFp0FA8LJZPgJKYsyyaKxUb+hTl0a7WAKPmkn64oadwaDdqrcXNFbm7B"
        "MwXmGPMH5M/dOjQFjw8UAXA2oeaghpNtFo/ah9onFvloLN4eOBPJkAh35/14E8Bbw9Bw5dl2LBhVRcerOla1H0OuX8ogOVyvWjf0"
        "c5RgwTyPxUwTWGZoMXze5y7uB6j1B5oDcW227gfAuo8279HwywIAuWQWX2M+/uqydve3RRUNDNFO75NUOEGn43YJg/9c9TfaWzK3"
        "nkdyh+AzrMeAH1GBd81NiYApARYHwtAtAnQ2kGzDTA5gV8FNWH+jv7QYv3wHA8Nd0eNAQbiAp+VRQ/AplCjbcfCb0buZ5kmSOrn1"
        "RVgOKQEMcnrZczJWoNQTsr5qKPcBtn8+6yG4cFhDm+ayImyj1Mz8FJSXT1fFNGk5RxX9X8edSWqn3y8YJxDp+o0GPg/Yz9oM41lm"
        "nNqLtAesQoHlPaKs+25JrEeJVwrqMgFMKVpAmvM6vcIkBnhw0T+BGgb7v+BoGlkKixrgTJA598MEG4Kar+CHT0sLizQAMyJpvgo2"
        "96vIgO7QB/WwQfzAkwOfT55AoRuoO/yGW94W9TdqRz9BZCvK8AGydueDtrNA+Dm642lf0RAY+Nfs1oI+b0uAGy2wGTf9rYoN7eGV"
        "oMJwHqzDG3SSNfLWlbSjNIHkvldz/7BrzPARMueA61D3TQxf7+wWs+2R/0Kai/6h8hdAFOmMW9HdwIHAHlbf1emdrO3P/u1BjIFB"
        "CL8pGRrViEbCn7nbG1ninaHAGgxUVzRUAMMGqqPICcOfewMBc93Xm3H1LdJnm9tNdgC66Qy15pF8clbWEeAse1veKA0VdjYTJopm"
        "jbZ2CYik0E+TSDkJvLwoBV6aICBNhpX0mNpgNE86oPT66IWAeA5h1es9rkUAKOZRbs36QLI3q51vWg3oY7AXsMXGf2zfYHuX2mXp"
        "wgamKmh9qCrC0WIs/4jmkKa0ZCJ3EwTeQ60UQA40bz8AU3hHMM0d0uTSACD3EcC3mpTnQDmjhUxt7xLATAcOjdzMJ6/JZrzddftc"
        "R9NjDzPIAAIMKVhPqajD9oPOkhCfwcw/6Ogt+xtD7wnPADzXiRaCWD3sZyQkHCtaMgvq8E+A79U2r/KdUJLtVfmebJozt4EG7W0B"
        "pjePxz0i2Y59jVv+w+VZvOaKtFYYhLfYZF+Gp7Pw7Ral4Jg2kQQwoeSG64Ar/jdEMBkbLTxm8JdDvL96PNgiPzMD/GZwfq6AEycV"
        "2+6lABD7mOZmoOOMPIuUt9b/KLZLDPH5rsBdgp0FhQAlQuVgSpAf4NJvyYKwJjirFMvl4ZD1jy7NRid75oADO2maoBxTlLfR16qW"
        "VZTo+4o6H2p74T+wwIMB7yaJhKmsks0gGHvm4POEAAhgG1pRgcfACpR5rUDgMRzOmLNH8MeVT6YBtiineSVgXaAyiXfGXwuCNwaL"
        "tB6WQHGw7ABXfomLLNP/bbjoDtL/SwFMO2DvWWqT5x/NBOpZW6Xm9568dNa1NBE6j56y5qqNBieCTC/1cyiaT8V+fuhvQio6WKWu"
        "3IOGmDa7AEcz5pV/3YYj2LRY7L0XvNGuWSvQ42lnPxzAFCJMq/EQrp56X3K5QiIpyqAEbHWyT/O59qbyMsPsOGWD95emj2Aqof4J"
        "evU4T5jARbOybeOsyW3k08NwzL5rGcbZY7nS7giQzv52kTydk0zTX/NdeNtaEMvopVHu0zkNtXHGIKKsqhbhZsx96+1DQhHBBhDB"
        "DRfjIFZkGgtxrXMO9BIzvhx+ljIpyqTeY4azMqSBLh/Z3yMphd9Dw+B2O9y8v0nzCzl5HNOQjzfr62JTEZS/shI0SKVcm3vpw5mZ"
        "jUAuyAaLFLSt8h7w9Sns2/x5ZpGCFPwYqJu2Z4Lwxr2o0MpYsK3syw38RuowUDH5SUqtnUM4HoAJmZPmaty+k3BCLpKWrsQKAy+g"
        "j7FGbSyGow+GDWYlSc4JbZ2s9ww9yCfHQyiZgf6ejQYUt01WGoGA582iPoXu8AoAJtv2/BTUS3DFAPlMBJZVje34xLsrdAffiH3e"
        "9n87urwaH62MqDJT0/QfK1J4N3CMg9TgDtdxhpIrYL5tuVhyuek1wV8x63pU07+WWsylc+0X/ykZBdIp4iJf8PyMM53JA62xfWVY"
        "JF8lSD1Ui/YbXLZyfXsvwVDTtldQTAshvmjOaNvZVNRZWOT70+gcx8KZwQeJVs5+WdB6xVoFSZKH2NsDPlJ+ltBbakDrTkIU+Tsa"
        "Geyy2802W+3MfPLWoN/C5/JCxsHsx+7h6emJ3Gj5Q19ToNBJ1fkejHlofMJsGG1jOQPnTJlipgkCX1IbI18mhIXfx4/wzCSr259D"
        "g/bRsAtsSwaaaPMc8748eMdLUewcr18ZhyKYQQNAgJRgB7Qa6YZQ38fCijfJXhYln3bw5ugBpgEh/e5AHaPgHGXvjXzgsN5cj6RP"
        "hUxes8bHE0ZHXdxuktBp8zKIO8T+GmPaj+NTj99MoJFAYxk+yUuXqCphA9GDfmw+lT0DvkEHuNnQijvcsSX5xeCptX/XGfhpvZkJ"
        "aZkdsUCZybDFCHvqxeuk+YDVH19IXlQWpdoP9fRbaFpuvJN5WZr4Mn3zj/xgF2fjPrQJFMziam5BrwnQHMIIOSaZoG3wF4g0Obn1"
        "Lb040CzKY/8aYLcfk5SY9mwRVOuzf2rEuVbzZDb6z/5mQf5JH6w1nIAURMZJ1OHRKxW5Zr02vmxnPNkbDDs/os/xgg9g6gwa69J6"
        "KAS57oB+STGvOy+q1tlU2ihmThzX7iLgVwE/sDLBDRlpyog5pVlgv9njDULNMcSzSlk5+F5Gv2yWv3gsKdEaIlgN5HP+rr+4FBvt"
        "C4zd/cXRv6S/lyHMlHk4lwg86bo9XFR5hcXVV6DLFpynY/HX/NOJOrPd+rkg4kTeGlTbvSfTHNj1S3Ow+cGR+PzzY9EPGzdNqxMm"
        "GTrw/0AUoPB/nAyYh/R+XGcZ0QQ68MvESWgeaIYwp1/JHCyPU0qic8a0OShvYfI55hh//QB+ivsLf+wsYx/2PgypH6XdKIe/ekjz"
        "lz2BDA4oK/X39YOV/u3NS8dYV5D0n9bY8Q59re1evnHW35vgsb6WP1x9lCI/PJcC2Ibb5n0H/h4i2IAq39JIrH4ej73Kyb+BCSW6"
        "k36Hxgpn8QaNCxFAAAAAElFTkSuQmCC\" alt=\"Medium One\"><div id=\"title\"><h2> Renesas S3A7 Kit Configuratio"
        "n </h2><div> Visit <a href=\"http://mediumone.com/renesas\">mediumone.com/renesas</a> for activation i"
        "nstructions and to learn more </div></div><div class=\"rounded_container\" id=\"network_config\"><table>"
        "<tr> <td></td> <td></td></tr><tr> <td class=\"align_right\">Wifi Network SSID:</td> <td> <input id=\"s\""
        " type=\"text\" name=\"m\" maxlength=\"255\" class=\"ssid1\" value=\"\"> </td></tr><tr> <td class=\"align_right\""
        ">Authentication Mode:</td> <td> <select id=\"am\" name=\"am\"> <option value=\"open\">Open</option> <optio"
        "n value=\"open\">Open</option> <option value=\"wep40bit\">WEP 40-bit Open Hex Key</option> <option value"
        "=\"wep128bit\">WEP 128-bit Open Hex Key</option> <option value=\"wpa\">WPA</option> <option value=\"wpa2\""
        " selected=\"\">WPA2</option> </select> </td></tr><tr> <td class=\"align_right\">WiFI Password:</td> <td>"
        " <input id=\"k\" type=\"text\" name=\"k\" maxlength=\"255\" class=\"ssid1\" value=\"\"> </td></tr><tr> <td class"
        "=\"align_right\">Project MQTT ID:</td> <td> <input id=\"m\" type=\"text\" name=\"m\" maxlength=\"255\" class=\""
        "ssid1\" value=\"\"> </td></tr><tr> <td class=\"align_right\">User MQTT ID:</td> <td> <input id=\"u\" type=\""
        "text\" name=\"u\" maxlength=\"255\" class=\"ssid1\" value=\"\"> </td></tr><tr> <td class=\"align_right\">API Ke"
        "y:</td> <td> <input id=\"a\" type=\"text\" name=\"a\" maxlength=\"255\" class=\"ssid1\" value=\"\"> </td></tr><t"
        "r> <td class=\"align_right\">API User Password:</td> <td> <input id=\"p\" type=\"text\" name=\"p\" maxlength"
        "=\"255\" class=\"ssid1\" value=\"\"> </td></tr><tr> <td colspan=\"2\" class=\"text-right\"> <input id=\"joinBut"
        "ton\" class=\"join_button\" type=\"button\" value=\"Connect\" onclick=\"joinNetwork();\"> </td></tr></table><"
        "/div><br><form method=\"post\" name=\"kickoff\" action=\"\"><input type=\"hidden\" id=\"ssid\" name=\"ssid\"/><i"
        "nput type=\"hidden\" id=\"sec\" name=\"sec\"/><input type=\"hidden\" id=\"key\" name=\"key\"/><input type=\"hidde"
        "n\" id=\"mqttprojectid\" name=\"mqttprojectid\"/><input type=\"hidden\" id=\"mqttuserid\" name=\"mqttuserid\"/>"
        "<input type=\"hidden\" id=\"apikey\" name=\"apikey\"/><input type=\"hidden\" id=\"password\" name=\"password\"/>"
        "</form></div><br><div id=\"footer\"> Copyright &copy; 2016, Medium One Inc. </div></div></body></html>"
        ;
